name: Weather-App - Rebuild Image & Update Deployment Repo
on:
  push:
    branches: [ "master" ]

jobs:
  Build-Push-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Configure AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run version script & update in S3
        run: |
          aws s3 cp s3://weather-app-version/.app_version ./.app_version
          NEW_VERSION=$(bash app_version_inc.sh patch)
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          aws s3 cp ./.app_version s3://weather-app-version/.app_version

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/weather-app-gunicorn:latest
      
    
  Update-Deploy-Repo:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: Make changes
        working-directory: ./argocd-deploy
        run: |
          echo ${GITHUB_RUN_NUMBER} >> test_trigger_file.txt

      - name: Checkout manifest Repo
        uses: actions/checkout@v4
        with:
          repository: Meron-Gelbard/argocd-deploy
          ref: main
          path: ./argocd-deploy
          persist-credentials: true
          token: ${{secrets.ARGO_TOKEN}}

      - name: Commit Changes
        working-directory: ./argocd-deploy
        run: |
          git config user.email "merongelbard@gmail.com"
          git config user.name "Meron-Gelbard"
          git add .
          git commit -m "${GITHUB_RUN_NUMBER}"

      - name: Push changes
        working-directory: ./argocd-deploy
        run: |
          git push
        

