name: Weather App Docker image re-build & push
on:
  push:
    branches: [ "master" ]

jobs:
  Build-Push-Docker:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: Checkout manifest Repo
        uses: actions/checkout@v4
        with:
          repository: Meron-Gelbard/argocd-deploy
          ref: main
          path: ./argocd-deploy

      - name: Make changes
        working-directory: ./argocd-deploy
        run: |
          echo ${GITHUB_RUN_NUMBER} >> test_trigger_file.txt

      - name: Commit and Push Changes
        working-directory: ./argocd-deploy
        run: |
          git config user.email "merongelbard@gmail.com"
          git config user.name "Meron-Gelbard"
          git remote set-url origin https://${{ secrets.ARGO_TOKEN }}@github.com/Meron-Gelbard/argocd-deploy
          git checkout main
          git add .
          git commit -m "${GITHUB_RUN_NUMBER}"
          git push