name: Weather-App - Rebuild Image & Update Deployment Manifest Repo
on:
  push:
    branches: [ "master" ]

jobs:
  Build-Push-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run version script & update in S3
        id: versioning
        run: |
          aws s3 cp s3://weather-app-version/.app_version ./.app_version
          NEW_VERSION=$(bash app_version_inc.sh minor)
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          aws s3 cp ./.app_version s3://weather-app-version/.app_version
      
      - name: Upload Version to github Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app_version_file
          path: .app_version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/weather-app-gunicorn:${{steps.versioning.outputs.NEW_VERSION}}
            ${{ secrets.DOCKER_USERNAME }}/weather-app-gunicorn:latest

  Update-Deploy-Repo:
    needs: Build-Push-Docker
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: Checkout manifest Repo
        uses: actions/checkout@v4
        with:
          repository: Meron-Gelbard/argocd-deploy
          ref: main
          path: ./argocd-deploy
          persist-credentials: true
          token: ${{secrets.ARGO_TOKEN}}
      
      - name: Download version file artifact
        uses: actions/download-artifact@v4
        with:
          name: app_version_file

      - name: Update Image Version
        id: version_update
        working-directory: ./argocd-deploy
        run: |
          NEW_VERSION=$(cat ../.app_version)
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          bash update_image_version.sh $NEW_VERSION

      - name: Commit Changes
        working-directory: ./argocd-deploy
        run: |
          git config user.email "merongelbard@gmail.com"
          git config user.name "Meron-Gelbard"
          git add .
          git commit -m "Deployment update to version: ${{steps.version_update.outputs.NEW_VERSION}}"

      - name: Push changes
        working-directory: ./argocd-deploy
        run: |
          git push
        

